### ISSUE TITLE
Heroku deploy broken

### ISSUE THREAD

**Issue by xavriley** [dblock/slack-google-bot#1]
By moving the "Deploy to Heroku" button to the `DEPLOYMENT.md` file this seems to break the request that Heroku uses to retrieve the `app.json` file.

If you click the button and look in the browser inspector you can see a 404 for the following url

https://api.github.com/repos/dblock/slack-google-bot/contents/app.json?ref=master%2FDEPLOYMENT

whereas this url works as expected

https://api.github.com/repos/dblock/slack-google-bot/contents/app.json?ref=master

**Comment by xavriley** [comment]
This could be fixed by changing the link to https://heroku.com/deploy?template=https://github.com/dblock/slack-google-bot/tree/master

However following that link returns the error

```
The content of app.json is not a valid JSON object.
```

so it looks like the `app.json` may need fixing up as well.

**Comment by dblock** [comment]
I'd love a pull request fixing this!

**Comment by dblock** [comment]
I believe I fixed this in https://github.com/dblock/slack-google-bot/commit/c63692ce5af3c56b2bce077ab1f620b11501eafc, it was just invalid JSON. Reopen if that's not the case.
