### ISSUE TITLE
Installation Step Question

### ISSUE THREAD

**Issue by jgates-fgsd** [dblock/slack-google-bot#2]
dblock, 

I apologize for the question but I have deployed using Heroku and have noted my API Token but I am stuck on the Environment step listed below. Where is this located so I can add that command? Thanks for the assistance!

Environment:
SLACK_API_TOKEN
Set SLACK_API_TOKEN from the Bot integration settings on Slack.
heroku config:add SLACK_API_TOKEN=...

**Comment by dblock** [comment]
Check out https://devcenter.heroku.com/articles/config-vars. You run this from your machine pointing at your app.

The "deploy to heroku" button could also ask you for this token. It would be a good feature request if you want to contribute something small and easy.
