### ISSUE TITLE
More than 1 result?

### ISSUE THREAD

**Issue by jandreaucodes** [dblock/slack-google-bot#6]
Is there any way for this pull in the top X results, instead of just one?

My use case would want it to see 3 or 5 results when searching.

**Comment by dblock** [comment]
It's a good feature request. It would need a tiny bit of work in https://github.com/dblock/slack-google-bot/blob/master/slack-google-bot/commands/google.rb. Give it a shot!

**Comment by mike-bailey** [comment]
Maybe an environment variable (unless I'm missing a config file somewhere) specifying how many you want returned??

**Comment by dblock** [comment]
I don't love environment variables although that's a start. Ideally it should be a persistent setting, like `bot set results 2`, or work it into the query like `who where the most important artists in 2015 /2`
